### ISSUE TITLE
Swift support for iOS

### ISSUE THREAD

**Issue by alexcohn** [DeNA/DeClang#6] opened 2021-07-28 05:52 UTC
I believe that this is on your roadmap, but just in case, let me file a feature request: to have the swift obfuscator support iOS targets, too.

**Comment by nevermoe** [comment] 2021-07-28 08:15
Do you mean this: [https://github.com/DeNA/DeClang/releases/tag/swift5.4-v1.1.0](https://github.com/DeNA/DeClang/releases/tag/swift5.4-v1.1.0) ?

**Comment by alexcohn** [comment] 2021-07-28 09:34
Yes, this is Mac OS only, isn't it?

**Comment by nevermoe** [comment] 2021-08-03 11:15
Duplicate of #5 .
Solved.

**Closed as completed by nevermoe** 2021-08-03 11:15 UTC

**Comment by alexcohn** [comment] 2021-08-17 21:18
Looks like the swift compiler did work.

**Comment by alexcohn** [comment] 2021-08-18 14:03
But what I am missing are the instructions to control swift obfuscation. Currently, I get unobfuscated binary for swift.
